using System;
using System.Collections.Generic;
using System.Text;
using SchemaForge.Crucible.Extensions;
using Newtonsoft.Json.Linq;

namespace SchemaForge.Crucible
{
  public abstract class ConfigToken
  {
    /// <summary>
    /// Name of the token; corresponds to a token present in the JObject that will be validated.
    /// </summary>
    public string TokenName { get; protected set; }
    /// <summary>
    /// String that will be added to the ErrorList of a Schema object as ErrorSeverity.Info when a validation error occurs for this token.
    /// </summary>
    public string HelpString { get; protected set; }
    /// <summary>
    /// Contains all the errors generated by validation functions.
    /// </summary>
    public List<Error> ErrorList { get; protected set; } = new();
    /// <summary>
    /// Indicates whether or not this token is required.
    /// </summary>
    public bool Required { get; protected set; }
  }
  public class ConfigToken<TCastType> : ConfigToken
  {
    /// <summary>
    /// If set and the token is optional, then if the user does not include this token in their configuration file, the default value will be inserted with TokenName as the property name.
    /// </summary>
    public TCastType DefaultValue { get; protected set; }
    public Constraint<TCastType>[] Constraints { get; protected set; }

    /// <summary>
    /// A ConfigToken represents a token that is expected to exist in the input JObject to a Schema object.
    /// </summary>
    /// <exception cref="ArgumentNullException">If inputName or inputHelpString is null, whitespace, or empty.</exception>
    /// <param name="inputName">Name of the token. This will be used to search the user config when validating.</param>
    /// <param name="inputHelpString">String that will be shown to the user in the event of a validation error.</param>
    /// <param name="inputValidationFunction">Function that will be executed on the corresponding value in the input config. Ideally created by ApplyConstraints().</param>
    public ConfigToken(string inputName, string inputHelpString, params Constraint<TCastType>[] inputConstraints)
    {
      BuildConfigToken(inputName, inputHelpString, true, inputConstraints);
    }

    /// <summary>
    /// A ConfigToken represents a token that is expected to exist in the input JObject to a Schema object.
    /// </summary>
    /// <exception cref="ArgumentNullException">If inputName or inputHelpString is null, whitespace, or empty.</exception>
    /// <param name="inputName">Name of the token. This will be used to search the user config when validating.</param>
    /// <param name="inputHelpString">String that will be shown to the user in the event of a validation error.</param>
    /// <param name="inputValidationFunction">Function that will be executed on the corresponding value in the input config. Ideally created by ApplyConstraints().</param>
    public ConfigToken(string inputName, string inputHelpString, bool required, params Constraint<TCastType>[] inputConstraints)
    {
      BuildConfigToken(inputName, inputHelpString, required, inputConstraints);
    }

    /// <summary>
    /// A ConfigToken represents a token that is expected to exist in the input JObject to a Schema object.
    /// </summary>
    /// <exception cref="ArgumentNullException">If inputName, inputDefaultValue, or inputHelpString is null, whitespace, or empty.</exception>
    /// <param name="inputName">Name of the token. This will be used to search the user config when validating.</param>
    /// <param name="inputHelpString">String that will be shown to the user in the event of a validation error.</param>
    /// <param name="inputDefaultValue">String that will be inserted into the user config if an optional token is not provided.</param>
    /// <param name="inputValidationFunction">Function that will be executed on the corresponding value in the input config. Ideally created by ApplyConstraints().></param>
    public ConfigToken(string inputName, string inputHelpString, TCastType inputDefaultValue, params Constraint<TCastType>[] inputConstraints)
    {
      BuildConfigToken(inputName, inputHelpString, false, inputDefaultValue, inputConstraints);
    }

    private void BuildConfigToken(string inputName, string inputHelpString, bool required, TCastType inputDefaultValue, params Constraint<TCastType>[] inputConstraints)
    {
      if (inputName.IsNullOrEmpty())
      {
        throw new ArgumentNullException(nameof(inputName));
      }
      if (inputHelpString.IsNullOrEmpty())
      {
        throw new ArgumentNullException(nameof(inputHelpString));
      }
      Required = required;
      TokenName = inputName;
      Constraints = inputConstraints;
      HelpString = inputHelpString;
      DefaultValue = inputDefaultValue;
    }

    private void BuildConfigToken(string inputName, string inputHelpString, bool required, ConstraintContainer<TCastType> constraintContainer)
    {
      if (inputName.IsNullOrEmpty())
      {
        throw new ArgumentNullException(nameof(inputName));
      }
      if (inputHelpString.IsNullOrEmpty())
      {
        throw new ArgumentNullException(nameof(inputHelpString));
      }
      Required = required;
      TokenName = inputName;
      Constraints = constraintContainer;
      HelpString = inputHelpString;
    }

    /// <summary>
    /// Executes the ConfigToken's ValidationFunction on the passed JToken.
    /// </summary>
    /// <param name="tokenValue">Token value to validate.</param>
    /// <returns>Bool indicating whether any fatal errors were found during validation.</returns>
    public bool Validate<TCollectionType,TValueType>(TCollectionType collection, ISchemaTranslator<TCollectionType,TValueType> translator)
    {
      (bool, TCastType) castResult = translator.TryCastToken<TCastType>(collection, TokenName);
      if(castResult.Item1)
      {
        ErrorList.AddRange(Constraints.ApplyConstraints(castResult.Item2, TokenName));
        return !ErrorList.AnyFatal();
      }
      else
      {
        ErrorList.Add(new Error($"Token {TokenName} with value {translator.CollectionValueToString(collection,TokenName)} is an incorrect type. Expected value type: {typeof(TCastType).Name}"));
        return false;
      }
    }
    public override string ToString() => TokenName;

    /// <summary>
    /// All equality operators compare the TokenName of two ConfigTokens to determine equality.
    /// </summary>
    /// <param name="obj">The other object to compare.</param>
    /// <returns>Bool indicating if two ConfigTokens have the same name.</returns>
    public override bool Equals(object obj) => this.Equals(obj as ConfigToken);

    /// <summary>
    /// All equality operators compare the TokenName of two ConfigTokens to determine equality.
    /// </summary>
    /// <param name="other">The other token to compare.</param>
    /// <returns>Bool indicating if two ConfigTokens have the same name.</returns>
    public bool Equals(ConfigToken other)
    {
      if(!other.Exists())
      {
        return false;
      }
      if(this.TokenName == other.TokenName)
      {
        return true;
      }
      else
      {
        return false;
      }
    }

    /// <summary>
    /// Sets the HashCode of a ConfigToken to the HashCode of its TokenName.
    /// </summary>
    /// <returns>HashCode of TokenName string.</returns>
    public override int GetHashCode() => TokenName.GetHashCode();
  }
}
